Finished requirements
yassineKtr/ATM-machine pull request #1
Opened 2022-05-21 01:16 UTC by yassineKtr

2022-05-23 19:15 UTC, Choukrijer requested changes

2022-05-23 19:15 UTC, Choukrijer commented on ATM/ATM.cs
> +            if (account == null) throw new InvalidOperationException("User not found");
faut retourner un false au lieux de faire un throw exception

2022-05-23 19:15 UTC, Choukrijer commented on ATM/ATM.cs
> +            var account = _accounts.FirstOrDefault(x => x.AccountPin == pin);
et s'il y a deux compte avec le meme pin et que t'as choisi le faux compte?

2022-05-23 19:15 UTC, Choukrijer commented on ATM/ATM.cs
> +        public bool SendMoneyNationaly(decimal amount, string accountNum)
il y a une duplication de code ici avec SendMoneyInternationaly on doit eviter le DRY pendant l'implementation et il faut faire un truc generic le max possible

2022-05-23 19:15 UTC, Choukrijer commented on ATM/AvailableAccounts.cs
> +public class AvailableAccounts
Cette classe est une fixture?? si c'est le cas il faut la renommer en XXXXFixture, puis tu l'utilises comme vrai fixture de test

2022-05-25 12:22 UTC, ismailoviic commented on ATM_Machine/Helpers/CurrencyConverter.cs
> +    private readonly static Dictionary<string, float> ConversionRates = new Dictionary<string, float>
un clean up ici

2022-05-26 22:41 UTC, closed without merging